version: 0.2

phases:
  install:
    commands:
      - echo Installing RSpec...
      - bundle install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Ruby code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - src/main.rb
